{{- if not .Values.supersync.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supersync.fullname" . }}
  labels:
    {{- include "supersync.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.supersync.secret.jwtSecret | quote }}
  {{- if and .Values.supersync.smtp.enabled (not .Values.supersync.smtp.existingSecret) }}
  SMTP_USER: ""
  SMTP_PASS: ""
  {{- end }}
{{- end }}
