export {
  PLAINSPACE_CONFIG_FORM_SECTION,
  PLAINSPACE_CONFIG_FORM,
  DEFAULT_PLAINSPACE_CFG,
} from './plainspace-cfg-form.const';

export const PLAINSPACE_POLL_INTERVAL = 5 * 60 * 1000;
export const PLAINSPACE_INITIAL_POLL_DELAY = 8 * 1000;
